#!/bin/sh

set -e
set -o xtrace

[ -n "${RELEASE}" ] || die "RELEASE must be set to either Precise or Quantal"

apt-get -y install software-properties-common

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list

apt-get update
