#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

cat > "/etc/rc.local" << _EOF_
# Make sure to disable Linux kernel feature transparent huge pages,
# it will affect greatly both memory usage and latency in a negative way.
# See: http://docs.mongodb.org/manual/tutorial/transparent-huge-pages/
if test -f /sys/kernel/mm/redhat_transparent_hugepage/defrag; then
  echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag
fi
if test -f /sys/kernel/mm/redhat_transparent_hugepage/enabled; then
  echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled
fi

exit \$?

_EOF_

cat <<EOL > /etc/yum.repos.d/mongodb.repo
[mongodb-org-2.6]
name=MongoDB 2.6 Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1
EOL

yum -y install -y mongodb-org-2.6.8 mongodb-org-server-2.6.8 mongodb-org-shell-2.6.8 mongodb-org-mongos-2.6.8 mongodb-org-tools-2.6.8

echo "exclude=mongodb-org,mongodb-org-server,mongodb-org-shell,mongodb-org-mongos,mongodb-org-tools" >> /etc/yum.conf

# DBAAS-238 - workaround issues in the shipped /etc/init.d/mongod
sed -i -e "s;^\(#\s*\)\?PIDFILE[ \t]*=.*;PIDFILE=\`awk -F=  '/^pidfilepath\\\s*=\\\s*/{gsub(/^[ \\t]+/, \"\", \$2)\; print \$2}' \"\$CONFIGFILE\"\`;" /etc/init.d/mongod
sed -i -e "s/.*init.d\/functions.*/SYSTEMCTL_SKIP_REDIRECT=true\n&/" /etc/init.d/mongod
echo "d /var/run/mongodb 0755 mongod mongod" > /lib/tmpfiles.d/mongodb.conf
sed -i -e "s;^\(#\s*\)\?dbpath[ \t]*=.*;dbpath = /var/lib/mongodb;" /etc/mongod.conf
sed -i -e "s;^\(#\s*\)\?logpath[ \t]*=.*;logpath = /var/log/mongodb;" /etc/mongod.conf
[ -d "/var/lib/mongo" ] && mv /var/lib/mongo /var/lib/mongodb
[ -d "/var/log/mongo" ] && mv /var/log/mongo /var/log/mongodb

# the following config changes are needed: smallfiles set to true, and bind_ip
# set to default
sed -i '/bind_ip/d' /etc/mongod.conf
sed -i '/smallfiles/d' /etc/mongod.conf
echo 'smallfiles = true' >> /etc/mongod.conf

chkconfig mongod on
