#!/bin/sh

set -e
set -o xtrace

yum install -y postgresql93-server postgresql93-contrib

# Though /var/lib/pgsql is the preferred directory, need to move it as
# this is where the volume will be mounted
su - postgres -c "/usr/pgsql-9.3/bin/initdb /var/lib/pgsql/9.3/data"
mv /var/lib/pgsql /var/lib/postgresql

mv /lib/systemd/system/postgresql-9.3.service /lib/systemd/system/postgresql.service

sed -i 's/PGDATA=\/var\/lib\/pgsql\/9.3\/data/PGDATA=\/var\/lib\/postgresql\/9.3\/data/' /lib/systemd/system/postgresql.service

# Create a volatile directory for runtime files.
echo "d /var/run/postgresql/ 0755 postgres postgres" > /lib/tmpfiles.d/postgresql.conf

# Install the native Python client.
yum install -y postgresql93-devel python-devel
pip install psycopg2

systemctl enable postgresql.service
systemctl start postgresql.service
