#!/bin/bash

set -eu
set -o pipefail

[ -n "$ARCH" ]
[ -n "$TARGET_ROOT" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

DIB_LOCAL_IMAGE=${DIB_LOCAL_IMAGE:-""}

if [ -n "$DIB_LOCAL_IMAGE" ]; then
    IMAGE_LOCATION=$DIB_LOCAL_IMAGE
    # No need to copy a local image into the cache directory, so just specify
    # the cached path as the original path.
    CACHED_IMAGE=$IMAGE_LOCATION
    BASE_IMAGE_FILE=`basename $DIB_LOCAL_IMAGE`
    BASE_IMAGE_TAR=$BASE_IMAGE_FILE.tgz
else
    # BASE_IMAGE_FILE=rhel-guest-image-7.0-20140930.0.x86_64.qcow2
    BASE_IMAGE_FILE=rhel-guest-image-7.1-20150224.0.x86_64.qcow2

    scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/$BASE_IMAGE_FILE $TMP_HOOKS_PATH/.

    IMAGE_LOCATION=$TMP_HOOKS_PATH/$BASE_IMAGE_FILE
    CACHED_IMAGE=$IMAGE_LOCATION

    export DIB_LOCAL_IMAGE=$IMAGE_LOCATION

    BASE_IMAGE_TAR=$BASE_IMAGE_FILE.tgz
fi

$TMP_HOOKS_PATH/bin/extract-image $BASE_IMAGE_FILE $BASE_IMAGE_TAR $IMAGE_LOCATION $CACHED_IMAGE
