#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

cat > "/etc/sysctl.d/10-cassandra-performance.conf" << _EOF_
# See 'http://docs.datastax.com/en/cassandra/2.1/cassandra/install/installRecommendSettings.html'
# for recommended production settings.
vm.max_map_count = 131072

_EOF_

echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list

apt-get install -qy wget
wget -O - http://debian.datastax.com/debian/repo_key | apt-key add -

apt-get update

apt-get install -y openjdk-7-jdk expect python-dev
apt-get install -y libxml2-dev ntp mc
apt-get install -y libxslt1-dev python-pexpect
apt-get install -y python-migrate build-essential

apt-get install -y dsc21=2.1.* cassandra=2.1.*

echo "cassandra hold" | dpkg --set-selections

service cassandra stop

# The Python Driver 2.0 for Apache Cassandra.
pip install cassandra-driver
# Sorted sets support for the Python driver.
pip install blist

rm -rf /var/lib/cassandra/data/system/*

service cassandra start
