#!/bin/sh

# PURPOSE: Temporary to ensure we have the latest version of maria
#          so that Mysql-python will compile

set -e
set -o xtrace

cat <<EOL > /etc/yum.repos.d/mariadb.repo
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/5.5/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOL

yum clean metadata
yum makecache
