#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

apt-get install curl
echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list
curl -L http://debian.datastax.com/debian/repo_key | apt-key add -

apt-get update

apt-get install -y openjdk-7-jdk expect python-dev
apt-get install -y libxml2-dev ntp mc
apt-get install -y libxslt1-dev python-pexpect
apt-get install -y python-migrate build-essential

apt-get install -y dsc20=2.0.11-1 cassandra=2.0.11

echo "cassandra hold" | dpkg --set-selections

service cassandra stop

rm -rf /var/lib/cassandra/data/system/*

service cassandra start
