#!/bin/sh

set -e
set -o xtrace

yum install -y http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-1.noarch.rpm

yum install -y postgresql94-server postgresql94-contrib

# Though /var/lib/pgsql is the preferred directory, need to move it as
# this is where the volume will be mounted
su - postgres -c "/usr/pgsql-9.4/bin/initdb /var/lib/pgsql/9.4/data"
mv /var/lib/pgsql /var/lib/postgresql

mv /lib/systemd/system/postgresql-9.4.service /lib/systemd/system/postgresql.service

sed -i 's/PGDATA=\/var\/lib\/pgsql\/9.4\/data/PGDATA=\/var\/lib\/postgresql\/9.4\/data/' /lib/systemd/system/postgre

systemctl enable postgresql.service
systemctl start postgresql.service
