#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# Instal the mysql community repository
yum -y install http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm

# Add yum utils to give us yum-config-manager
yum -y install yum-utils

# Setup the version of mysql we want
yum-config-manager --disable mysql56-community
yum-config-manager --enable mysql55-community

yum -y install mysql-community-server percona-xtrabackup

# add and include for /etc/my.cnf.d to /etc/my.cnf
MYSQL_CONF_D="/etc/my.cnf.d/"
mkdir -p "$MYSQL_CONF_D"
echo "!includedir $MYSQL_CONF_D" >> "/etc/my.cnf"

systemctl enable mysqld
