#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# Instal the mysql community repository
yum -y install http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm

# Add yum utils to give us yum-config-manager
yum -y install yum-utils

# Setup the version of mysql we want
yum-config-manager --disable mysql56-community
yum-config-manager --enable mysql55-community

yum -y install mysql-community-server percona-xtrabackup

# DBAAS-904 - code expects /etc/my.cnf and /etc/mysql/conf.d
BASE_MY_CNF_FILE="/etc/my.cnf"
MYSQL_CONF_D_DIR="/etc/mysql/conf.d"
mkdir -p "$MYSQL_CONF_D_DIR"
echo "!includedir $MYSQL_CONF_D" >> "$BASE_MY_CNF_FILE"

# DBAAS-424 - fix the mysql-systemd-start script to use the correct socket
sed -i '/get_option  mysqld socket/s/$datadir/\/var\/lib\/mysql/' /usr/bin/mysql-systemd-start

systemctl enable mysqld
