#!/bin/sh

set -e
set -o xtrace

[ -n "${RELEASE}" ] || die "RELEASE must be set to either Precise or Quantal"

apt-get -y install software-properties-common

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

apt-get update
