#!/bin/bash

set -e
set -o xtrace

# CONTEXT: HOST prior to IMAGE BUILD as SCRIPT USER
# PURPOSE: Download the DB2 Express-C v10.5 packages to a directory on the local filesystem or
#          to a private repository. The download location is specified using the env variable:
#          DATASTORE_PKG_LOCATION

[ -n "${TMP_HOOKS_PATH}" ] || die "Temp hook path not set"

scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/db2-express-10.5/v10.5_linux64_expc.tar.gz $TMP_HOOKS_PATH/.
