#!/bin/bash

# CONTEXT: root in the chroot?

set -eu
set -o pipefail

CIVERSION="0.7.5"
CITOOLSVERSION_WEB="0.16.orig"
CITOOLSVERSION_FOLDER="0.16"
WORKSPACE="/tmp/ci_install"
# RHEL 6.x has 0.7.4 from EPEL. We'd prefer 0.7.5
if [ ! -f "/etc/redhat-release" ] ; then
    exit;
fi

yum install -y wget
mkdir -p "$WORKSPACE" && cd "$WORKSPACE"

wget https://launchpad.net/cloud-init/trunk/$CIVERSION/+download/cloud-init-$CIVERSION.tar.gz
tar xvzf cloud-init-$CIVERSION.tar.gz

pushd cloud-init-$CIVERSION
# this will overwrite the vendor's cloud-init configuration provided in the cloud image.
python setup.py install
popd

# install growpart
wget https://launchpad.net/cloud-initramfs-tools/trunk/0.16/+download/cloud-initramfs-tools_$CITOOLSVERSION_WEB.tar.gz
tar xvzf cloud-initramfs-tools_$CITOOLSVERSION_WEB.tar.gz 
pushd cloud-initramfs-tools-$CITOOLSVERSION_FOLDER*
make install
popd

rm -rf "$WORKSPACE"

# long winded way of setting distro: rhel
cat > /etc/cloud/cloud.cfg <<'_EOF_'

# The top level settings are used as module
# and system configuration.

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
   - default

# If this is set, 'root' will not be able to ssh in and they 
# will get a message to login instead as the above $user (ubuntu)
disable_root: true

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# Example datasource config
# datasource: 
#    Ec2: 
#      metadata_urls: [ 'blah.com' ]
#      timeout: 5 # (defaults to 50 seconds)
#      max_wait: 10 # (defaults to 120 seconds)

# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - seed_random
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ca-certs
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
# Emit the cloud config ready event
# this can be used by upstart jobs for 'start on cloud-config'.
 - emit_upstart
 - disk_setup
 - mounts
 - ssh-import-id
 - locale
 - set-passwords
 - landscape
 - timezone
 - puppet
 - chef
 - salt-minion
 - mcollective
 - disable-ec2-metadata
 - runcmd

# The modules that run in the 'final' stage
cloud_final_modules:
 - rightscale_userdata
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message
 - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: rhel
   # Default user name + that default users groups (if added/used)
   default_user:
     name: ubuntu
     lock_passwd: True
     gecos: Ubuntu
     groups: [adm, audio, cdrom, dialout, dip, floppy, netdev, plugdev, sudo, video]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
#   ssh_svcname: ssh

_EOF_



rm -rf /tmp/ci_install
