#!/bin/bash

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install trove guest python dependencies - see redstack functions_qemu

set -e
set -o xtrace

yum -y install http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

yum -y update

yum install -y python-devel libxml2-devel libxslt-devel python-setuptools python-pip python-sqlalchemy python-lxml \
    python-routes python-eventlet python-webob python-kombu python-paste-deploy python-paste python-netaddr \
    python-httplib2 python-iso8601 python-pexpect MySQL-python python-migrate python-anyjson gcc 

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py

pip install extras python-novaclient python-swiftclient python-cinderclient \
    kombu>2.4.7 six babel python-heatclient passlib jinja2  python-neutronclient netifaces \
    oslo.config>=1.2.0 oslo.messaging>=1.4.0 oslo.i18n>=1.0.0 oslo.serialization>=1.0.0 oslo.utils>=1.0.0 \
    osprofiler>=0.3.0
