#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install Percona-Server-shared-56 Percona-Server-server-56 Percona-Server-client-56 percona-xtrabackup
