#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install Percona-Server-shared-56 Percona-Server-server-56 Percona-Server-client-56 percona-xtrabackup

mkdir /etc/mysql
mkdir /etc/mysql/conf.d/

if [ -f /etc/my.cnf ]; then
    echo "!includedir /etc/mysql/conf.d/" >> /etc/my.cnf
    mv /etc/my.cnf /etc/mysql/my.cnf
fi

systemctl enable mysqld
