#!/bin/sh

set -e
set -o xtrace

[ -n "${RELEASE}" ] || die "RELEASE must be set to either Trusty or Quantal"

apt-get -y install software-properties-common

add-apt-repository -y ppa:couchdb/stable

apt-get -y update
