#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

yum -y install java dsc21

pip install -U setuptools

# The Python Driver 2.0 for Apache Cassandra.
pip install cassandra-driver blist

systemctl start cassandra 
chkconfig cassandra on
