#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

yum -y install java dsc21

pip install -U setuptools

# The Python Driver 2.0 for Apache Cassandra.
pip install cassandra-driver blist

# Create a volatile directory for PID.
echo "d /var/run/cassandra/ 0755 cassandra cassandra" > /lib/tmpfiles.d/cassandra.conf

systemctl start cassandra
chkconfig cassandra on
