#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install Percona-Server-shared-55 Percona-Server-server-55 Percona-Server-client-55 percona-xtrabackup-22

# DBAAS-904 - code expects /etc/my.cnf and /etc/mysql/conf.d
BASE_MY_CNF_FILE="/etc/my.cnf"
MYSQL_CONF_D_DIR="/etc/mysql/conf.d"
mkdir -p "$MYSQL_CONF_D_DIR"
echo "!includedir $MYSQL_CONF_D_DIR" >> "$BASE_MY_CNF_FILE"

systemctl enable mysqld
