#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install Percona-Server-shared-55 Percona-Server-server-55 Percona-Server-client-55 percona-xtrabackup

# add an include for /etc/my.cnf.d to /etc/my.cnf
MYSQL_CONF_D="/etc/my.cnf.d/"
mkdir -p "$MYSQL_CONF_D"
echo "!includedir $MYSQL_CONF_D" >> "/etc/my.cnf"

systemctl enable mysqld
