#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# root can not sudo without a tty by default.
echo "Defaults:root !requiretty" >> /etc/sudoers.d/root-notty
chmod 0440 /etc/sudoers.d/root-notty
visudo -c
