#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# heat-admin can not sudo without a tty by default
echo 'Defaults:heat-admin !requiretty' >> /etc/sudoers.d/heat-admin-notty
chmod 0440 /etc/sudoers.d/heat-admin-notty
visudo -c
