#!/bin/sh

set -e
set -o xtrace

cat <<EOL > /etc/yum.repos.d/datastax.repo
[datastax]
name = DataStax Repo for Apache Cassandra
baseurl = http://rpm.datastax.com/community
enabled=1
gpgcheck=0
EOL

yum clean metadata
yum makecache

