#!/bin/bash

set -e
set -o xtrace

# TEMP
# yum -y install http://rdoproject.org/repos/openstack-liberty/rdo-release-liberty.rpm
yum -y install http://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm
yum-config-manager --add-repo http://trunk.rdoproject.org/centos70/current/delorean.repo
