#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

mkdir /var/lib/mysql

yum -y install MariaDB-server MariaDB-client percona-xtrabackup

mkdir /etc/mysql
mkdir /etc/mysql/conf.d/

chkconfig mysql on
