#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

apt-get -y install mongodb-org=2.6.8 mongodb-org-server=2.6.8 mongodb-org-shell=2.6.8 mongodb-org-mongos=2.6.8 mongodb-org-tools=2.6.8

# We want to enable smallfiles on boot to speed things up
# Knowing that after boot Trove will replace the configuration
# file with something that doesn't have smallFiles enabled

# Note: 2.6 on ubuntu still appears to use the old non-YAML file format
echo "smallfiles=true" >> /etc/mongod.conf
