#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -ex

mkdir /etc/redis
mkdir /etc/redis/conf.d

yum -y install redis
service redis start
