#!/bin/bash

set -eux
set -o pipefail

# BH: remove to work around reboot issue. Revert to previous behavior

CONFIGURED_SELINUX=$(grep ^SELINUX= /etc/selinux/config | awk -F = '{print $2}')

case "$CONFIGURED_SELINUX" in
    "enforcing"|"permissive")
        # Without fixing selinux file labels, sshd will run in the kernel_t domain
        # instead of the sshd_t domain, making ssh connections fail with
        # "Unable to get valid context for <user>" error message
        setfiles /etc/selinux/targeted/contexts/files/file_contexts /
        ;;
esac

# the only other value is disabled. I'm not sure we ever need to label on boot.
if false; then
    echo "Skipping SELinux relabel, since setfiles is not available."
    echo "Touching /.autorelabel to schedule a relabel when the image boots."
    touch /.autorelabel
fi

