#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5

cat <<EOL > /etc/apt/sources.list.d/mysql.list
deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7
EOL

apt-get -y update

apt-get -y install libmysqlclient18 mysql-server-5.7 percona-xtrabackup-22
