#!/bin/bash

set -e
set -o xtrace

source $_LIB/die

[ -n "$TMP_HOOKS_PATH." ] || die "Temp hook path not set"

scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/oracle-12.1/linuxamd64_12102_database_1of2.zip $TMP_HOOKS_PATH/.
scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/oracle-12.1/linuxamd64_12102_database_2of2.zip $TMP_HOOKS_PATH/.
scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/oracle-12.1/oracle-rdbms-server-12cR1-preinstall-1.0-3.el7.x86_64.rpm $TMP_HOOKS_PATH/.
