#!/bin/bash

set -e
set -o xtrace

pkg="V77246-01.tar.gz"

[ -n "${TMP_HOOKS_PATH}" ] || die "Temp hook path not set"

scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/mysqlee-5.6/MySQL-client-advanced-5.6.26-1.el7.x86_64.rpm $TMP_HOOKS_PATH/.
scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/mysqlee-5.6/MySQL-server-advanced-5.6.26-1.el7.x86_64.rpm $TMP_HOOKS_PATH/.
scp -o StrictHostKeyChecking=no gw2.elasticdb.org:/mnt/opt/build/mysqlee-5.6/MySQL-shared-advanced-5.6.26-1.el7.x86_64.rpm $TMP_HOOKS_PATH/.
