#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Set mysql to start manual

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

disable_service() {
    if [ -f "/etc/init/$1.conf" ]; then
       echo manual >> "/etc/init/$1.conf"
    elif [ -f "/etc/init.d/$1" ]; then
       if [ -f "/usr/sbin/update-rc.d" ]; then
           update-rc.d $1 defaults; sudo update-rc.d $1 disable
       elif [ -f "/sbin/chkconfig" ]; then
           sudo chkconfig $1 off
       fi
    elif [ -f "/lib/systemd/system/$1.service" ]; then
        systemctl disable $1
    fi
}

disable_service mysql
disable_service mysqld
disable_service mysql-server
